---
- name: "Main Ansible playbook"
  hosts: localhost
  connection: local
  tasks:

  - name: "Update Cache"
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 3600
  
  - name: "Update all packages"
    become: yes
    apt:
      name: "*"
      state: latest

  - name: "Install Desktop Components"
    become: yes
    apt:
      pkg:
      - xfce4
      - xfce4-goodies
      - i3
      - lightdm
      state: latest

  - name: "Install Packages"
    become: yes
    apt:
      pkg:
      - git
      - tmux
      - lxappearance
      - build-essential
      - arandr
      - bear
      - libreoffice
      - texlive
      - thunderbird
      state: latest
