---
- name: "Add Spotify Repository Key"
  become: yes
  apt_key:
    url: "https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg"
    state: present

- name: "Add Spotify Repository"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] http://repository.spotify.com stable non-free"
    state: present
    filename: spotify-client
    update_cache: yes

- name: "Install Spotify"
  become: yes
  apt:
    pkg: spotify-client
    state: present
