---
- name: "Download Veracrypt Deb Package"
  get_url:
    url: "{{ veracrypt_link }}"
    dest: "{{ lookup('env','HOME') }}/Downloads"
    mode: '0700'

- name: "Download Veracrypt Deb Package Signature"
  get_url:
    url: "{{ veracrypt_sig }}"
    dest: "{{ lookup('env','HOME') }}/Downloads"
    mode: '0700'

- name: "Download Veracrypt PGP Public Key"
  get_url:
    url: "{{ veracrypt_pgp_key }}"
    dest: "{{ lookup('env','HOME') }}/Downloads"
    mode: '0700'

## TODO:
# 1. validate downloaded deb package
# 2. install deb package
